#! /usr/bin/env python
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
#
# Copyright © 2016 yqiu <yqiu@f24-suntzu>
#
# Distributed under terms of the MIT license.

builds = ["A D White House", "Alice Cook House", "American Indian Program House",
         "Anabel Taylor Hall", "Anna Comstock House", "Appel Commons",
         "Bailey Hall", "Baker Complex", "Baker Lab",
         "Baker South", "Baker Tower", "Balch Hall",
         "Bard Hall", "Barnes Hall", "Bartels Hall",
         "Barton Hall", "Beebe Hall", "Big Red Barn",
         "Biotechnology Building", "Boldt Tower", "Boyce Thompson Institute",
         "Bradfield Hall", "Bruckner Lab", "Caldwell Hall",
         "Campus Store", "Carl Becker House", "Carpenter Hall",
         "Cascadilla Hall", "Clara Dickson Hall",
         "Clark Hall", "Computing Communications Center",
         "Comstock Hall", "Corson Mudd Complex", "Court Hall",
         "Day Hall", "Delta Tau Delta", "Diagnostic Lab",
         "Duffield Hall", "East Campus Research Facility", "Emerson Hall",
         "Fernow Hall", "Fischell Band Center", "Flora Rose House",
         "Food Science Lab", "Founders Hall", "Foundry",
         "Friedman Strength Conditioning Center", "Friedman Wrestling Center", "Gannett Health Center",
         "Gates Hall", "George Jameson Hall", "Goldwin Smith Hall",
         "Grumman Hall", "Grumman Squash Court",
         "Guterman Bioclimatic Lab", "Hans Bethe House", "Helen Newman Hall",
         "Hollister Hall", "Hughes Hall",
         "Human Ecology Building", "Humphreys Service Building", "Hurlburt House",
         "ILR Conference Center", "International Living Center", "Ithaca High School",
         "Ives Hall", "Ives Hall East", "Ives Hall Faculty Wing",
         "Ives Hall West", "Johnson Museum Of Art", "Kay Hall",
         "Ken Post Lab", "Kennedy Roberts Hall", "Kimball Hall",
         "Kroch Library", "Large Animal Research Teaching Unit", "Lincoln Hall",
         "Lynah Rink", "Lyon Hall", "Malott Hall",
         "Mann Library", "Mann Library Addition", "Martha VanRensselaer Complex",
         "Martha VanRensselaer Hall", "Martha VanRensselaer West", "Mary Donlon Hall",
         "Mews Hall", "McGraw Hall", "Milstein Hall",
         "Morrill Hall", "Morrison Hall", "Myron Taylor Hall",
         "Muenscher Lab", "Newman Lab", "North Campus High Rise 5",
         "North Campus Low Rise 6", "North Campus Low Rise 7", "North Campus Low Rise 9",
         "North Campus Hot Water Radiation Loop", "Noyes Community Recreation Center", "Noyes Lodge",
         "Olin Chemistry Research Wing", "Olin Hall", "Olin Library",
         "Phi Kappa Psi", "Phillips Hall",
         "Physical Sciences", "Plant Science",
         "Rand Hall", "Rhodes Hall",
         "Rice Hall", "Riley Robb Hall", "Risley Hall",
         "Robert Purcell Community Center", "Robert W Holley Center", "Rockefeller Hall",
         "Sage Chapel", "Sage Hall", "Savage Hall",
         "Schoellkopf Crescent", "Schoellkopf Field", "Schoellkopf Hall",
         "Schurman Hall", "Schurman North", "Schwartz Center For Performing Arts",
         "Sheldon Court", "Sibley Hall", "Sigma Phi",
         "Snee Hall", "Space Sciences Building", "Statler Hall",
         "Statler Hotel", "Stimson Hall", "Stocking Hall",
         "Stocking Hall East Addition", "Teagle Hall", "Tjaden Hall",
         "Ujamaa Residential College", "Upson Hall", "Uris Hall",
         "Uris Library", "Vet Diagnostic Lab", "Vet Education Center",
         "Vet Medical Annex", "Vet Medical Center", "Vet Research Tower",
         "Ward Lab", "Warren Hall", "Water Filtration Plant",
         "Weill Hall", "White Hall",
         "William Keeton House", "Wilson Lab", "Willard Straight Hall",
         "Wing Hall", "Wing Hall Wing"]

